server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Testzl?serverTimezone=UTC
    username: 'root'
    password: 'mysql333'

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true